version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18

    commands:
      - echo Installing tauri build deps
      - apt-get install libgtk-3-dev libsoup2.4
      - echo Installing NPM packages at `date`
      - npm install
      - echo NPM packages installed successfully at `date`

  build:
    commands:
      - echo Beginning caraontime build at `date`
      - npm run tauri build
              
    finally:
      - echo Finished caraontime build at `date`
            
artifacts:
  files:
    - 'target/caraontime'